[package]
name = "dice-rts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_rapier3d = "0.17.0"
rand = "0.8.5"
bevy_mod_picking = "0.9"
bevy-inspector-egui = "0.12.1"